In [43]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [44]:
dataset = pd.read_csv ('datasets/ANN.csv')
X = dataset.iloc[: :-1].values
y = dataset.iloc[:, -1].values

In [45]:
print(X)

[[4.000e+00 5.000e+00 1.280e+05 8.500e+00 8.508e+03 1.000e+00]
 [4.000e+00 5.000e+00 1.360e+05 8.500e+00 9.064e+03 1.000e+00]
 [2.000e+00 5.000e+00 1.360e+05 8.500e+00 9.863e+03 1.000e+00]
 [4.000e+00 5.000e+00 1.360e+05 8.000e+00 6.650e+03 1.000e+00]
 [4.000e+00 4.000e+00 1.090e+05 1.000e+01 1.003e+04 1.000e+00]
 [2.000e+00 6.000e+00 1.520e+05 9.000e+00 5.344e+03 1.000e+00]
 [2.000e+00 4.000e+00 1.300e+05 9.000e+00 9.694e+03 1.000e+00]
 [2.000e+00 4.000e+00 1.300e+05 9.000e+00 9.109e+03 1.000e+00]]


In [46]:
print(y)

[1 1 1 1 1 1 1 1]


In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2, random_state = 0)

In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [49]:
from tensorflow import keras

In [50]:
from tensorflow.keras import layers

In [51]:
model = tf.keras.models.Sequential()

In [52]:
model.add(layers.Dense(5, activation = 'relu'))
model.add(layers.Dense(5, activation = 'relu'))
model.add(layers.Dense(5, activation = 'relu'))

In [53]:
model.add(layers.Dense(1, activation = 'sigmoid'))

In [54]:
model.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [55]:
# now train the set
model.fit(X_train, y_train, epochs = 100)

Epoch 1/100
1/1 [==============================] - 0s 451ms/step - loss: 0.4289 - accuracy: 1.0000
Epoch 2/100
1/1 [==============================] - 0s 4ms/step - loss: 0.4245 - accuracy: 1.0000
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.4201 - accuracy: 1.0000
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 0.4158 - accuracy: 1.0000
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.4115 - accuracy: 1.0000
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 0.4073 - accuracy: 1.0000
Epoch 7/100
1/1 [==============================] - 0s 4ms/step - loss: 0.4031 - accuracy: 1.0000
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 0.3989 - accuracy: 1.0000
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3946 - accuracy: 1.0000
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 0.3904 - accuracy: 1.0000
Epoch 11/100
1/1 [=========

In [59]:
print(model.predict(sc.transform([[2,4,130000,9,9109,0]])) > 0.5)

1/1 [==============================] - 0s 106ms/step
[[ True]]


In [61]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
print (y_test, y_pred)

1/1 [==============================] - 0s 18ms/step
[1 1] [[ True]
 [ True]]


In [62]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test, y_pred)
print (cm)

[[2]]


In [63]:
from sklearn.metrics import accuracy_score
ac = accuracy_score (y_test, y_pred)
print (ac)

1.0
