In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv ('datasets/LRCar_Data.csv')
x = dataset.iloc[: :-1].values
y = dataset.iloc[:, -1].values

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (x, y, test_size = 0.2, random_state = 0)

In [4]:
print (X_train)

[[3.0000e+00 9.6000e+00 2.0000e+00 5.0000e+00 3.7730e+03 1.0000e+00]
 [1.9000e+01 4.0000e+00 3.4000e+00 5.0000e+00 8.1360e+03 1.0000e+00]
 [1.3000e+01 5.3000e+00 3.0000e+00 7.0000e+00 5.6960e+03 1.0000e+00]
 [8.0000e+00 7.9000e+00 2.2000e+00 5.0000e+00 5.4450e+03 1.0000e+00]
 [2.5000e+01 2.9000e+00 1.8000e+00 5.0000e+00 1.0943e+04 1.0000e+00]
 [1.4000e+01 5.1000e+00 2.0000e+00 5.0000e+00 5.7080e+03 1.0000e+00]
 [2.2000e+01 3.2000e+00 1.8000e+00 5.0000e+00 9.8270e+03 1.0000e+00]
 [1.6000e+01 4.5000e+00 1.8000e+00 7.0000e+00 6.7940e+03 1.0000e+00]
 [7.0000e+00 8.2000e+00 1.6000e+00 5.0000e+00 6.0150e+03 0.0000e+00]
 [1.0000e+01 6.8000e+00 2.2000e+00 5.0000e+00 5.7190e+03 1.0000e+00]
 [2.9000e+01 1.3000e+00 2.2000e+00 7.0000e+00 1.2239e+04 1.0000e+00]
 [1.0000e+00 1.0500e+01 1.6000e+00 5.0000e+00 3.9340e+03 0.0000e+00]
 [2.4000e+01 3.0000e+00 3.2000e+00 7.0000e+00 1.1381e+04 1.0000e+00]
 [2.6000e+01 2.2000e+00 3.4000e+00 5.0000e+00 1.0558e+04 1.0000e+00]
 [1.2000e+01 5.9000e+00 1.8000e+00

In [5]:
print (y_train)

[1 1 0 1 0 1 0 0 1 1 0 1 0 0 1 0 1 1 1 0 0 1 1 1]


In [6]:
print (X_test)

[[2.8000e+01 1.5000e+00 1.4000e+00 5.0000e+00 1.1264e+04 1.0000e+00]
 [2.0000e+00 1.0300e+01 1.8000e+00 5.0000e+00 4.6210e+03 0.0000e+00]
 [1.7000e+01 4.1000e+00 1.8000e+00 5.0000e+00 6.6030e+03 1.0000e+00]
 [2.0000e+01 3.9000e+00 1.8000e+00 5.0000e+00 9.3940e+03 0.0000e+00]
 [4.0000e+00 9.5000e+00 1.6000e+00 7.0000e+00 4.3530e+03 0.0000e+00]
 [6.0000e+00 8.7000e+00 2.4000e+00 5.0000e+00 5.6640e+03 0.0000e+00]]


In [7]:
print (y_test)

[1 1 1 0 1 1]


In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
print (X_train)

[[-1.58635817  1.75832984 -0.39913716 -0.64168895 -1.46842727  0.64168895]
 [ 0.34136821 -0.40973925  1.91310572 -0.64168895  0.14048311  0.64168895]
 [-0.38152918  0.09356251  1.25246489  1.55838744 -0.75929716  0.64168895]
 [-0.98394368  1.10016601 -0.06881675 -0.64168895 -0.85185653  0.64168895]
 [ 1.06426561 -0.83560996 -0.72945758 -0.64168895  1.17559919  0.64168895]
 [-0.26104628  0.01613147 -0.39913716 -0.64168895 -0.75487201  0.64168895]
 [ 0.70281691 -0.7194634  -0.72945758 -0.64168895  0.76406034  0.64168895]
 [-0.02008048 -0.21616165 -0.72945758  1.55838744 -0.35439604  0.64168895]
 [-1.10442658  1.21631257 -1.05977799 -0.64168895 -0.64166195 -1.55838744]
 [-0.74297788  0.6742953  -0.06881675 -0.64168895 -0.75081563  0.64168895]
 [ 1.54619721 -1.45505827 -0.06881675  1.55838744  1.65351527  0.64168895]
 [-1.82732397  2.10676952 -1.05977799 -0.64168895 -1.40905652 -1.55838744]
 [ 0.94378271 -0.79689444  1.5827853   1.55838744  1.33711712  0.64168895]
 [ 1.18474851 -1.1066186 

In [10]:
from sklearn.svm import LinearSVC
classifier = LinearSVC (random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\marce\anaconda3\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


LinearSVC(random_state=0)

In [12]:
print(classifier.predict(sc.transform([[1.1,2.4,5,12187]])))

ValueError: X has 4 features, but StandardScaler is expecting 6 features as input.

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
print (y_pred, y_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test, y_pred)
print (cm)

In [ ]:
from sklearn.metrics import accuracy_score
ac = accuracy_score (y_test, y_pred)
print (ac)